### ISSUE TITLE
Add support for Jewish dusk

### ISSUE THREAD

**Issue by rosenbergj** [mfreeborn/heliocron#20]
It would be great if the `wait` command of this project could support "Jewish dusk", more commonly known as the time in the evening when the ritual of havdalah is done. (Other names for this time that you'll find if you look around the web are "tzeit hakochavim" or "the appearance of three stars".) The time for this is not universally agreed upon, but the most commonly used time is when the center of the sun is 8.5 degrees below the horizon.

**Comment by mfreeborn** [comment]
closed by #26 which is currently on master.

You will be able to specify something like:
`heliocron -d 2020-12-28 wait --event custom_pm --altitude 8.5`

**Comment by rosenbergj** [comment]
Thank you!!
