### ISSUE TITLE
compilation errors on cubieboard 1

### ISSUE THREAD

**Issue by scimmiettarossa** [mfreeborn/heliocron#22]
I'm trying to compile heliocorn on a cubieboard1 running armbian, and I'm getting the following errors:

> error[E0599]: no method named "as_deref" found for type "std::option::Option<std::string::String>" in the current scope
>    --> src/config.rs:140:37
>     |
> 140 |                 date_args.time_zone.as_deref(),
>     |                                     ^^^^^^^^ help: did you mean: "as_ref"
> 
> error[E0658]: use of unstable library feature 'range_contains': recently added as per RFC (see issue #32311)
>    --> src/structs.rs:141:39
>     |
> 141 |                     n if (0.0..=90.0).contains(&n) => Ok(n),
>     |                                       ^^^^^^^^
> 
> error[E0658]: use of unstable library feature "range_contains": recently added as per RFC (see issue #32311)
>    --> src/structs.rs:197:40
>     |
> 197 |                     n if (0.0..=180.0).contains(&n) => Ok(n),
>     |                                        ^^^^^^^^
> 
> error: aborting due to 3 previous errors
> 
> Some errors occurred: E0599, E0658.
> For more information about an error, try "rustc --explain E0599".
> error: Could not compile "heliocron".

I've tried to understand a bit more about the errrs, but with no luck... do you have any idea?

thanks
rosanna

**Comment by mfreeborn** [comment]
Unfortunately I don't own a cubieboard to test on; all tests are passing on the architectures explicitly supported.
