### ISSUE TITLE
Getting Illegal Instruction when attempting to run on Raspberry Pi Zero W with latest OS

### ISSUE THREAD

**Issue by chrisndeca** [mfreeborn/heliocron#23]
I have tried both the full version of the Raspbian OS and the light version and it is happening with both OSes. I think it might be a hardware issue, because the version of heliocron for my Pi3+ runs just fine on the latest OS. This is happening on the prebuilt binary additional for the Pi1/0. 

Please let me know if you need any further information.

**Comment by mfreeborn** [comment]
Thanks for raising this issue - I hadn't actually tried it on my RPi 0. The problem was that I needed to change the target triple to be of a non-hard float variety.

The short of it is, 0.5.0 has now been released and I have personally verified that the prebuilt binary runs on my RPi Zero W.
