### ISSUE TITLE
Feature Request: Add 'tag' or 'comment' parameter.

### ISSUE THREAD

**Issue by slynn1324** [mfreeborn/heliocron#24]
Because these processes run for a prolonged period of time -- it would be nice to be able to include some sort of 'tag' or 'comment' parameter, so that the purpose of the heliocron process could be identified more easily via 'ps'.  The parameter/value doesn't need to actually do anything - but including one currently causes an error for an invalid parameter.

**Comment by mfreeborn** [comment]
Sounds like a good idea - I'll look into it this weekend
