### ISSUE TITLE
heliocron is now a package on NetBSD

### ISSUE THREAD

**Issue by voidpin** [mfreeborn/heliocron#29]
FYI, https://mail-index.netbsd.org/pkgsrc-changes/2021/01/01/msg225992.html

Regards

**Comment by mfreeborn** [comment]
Nice! Looks like it's got the outdated 0.4.0 version, however.

**Comment by voidpin** [comment]
Hmm... Why so?
```
+# $NetBSD: Makefile,v 1.1 2021/01/01 14:13:34 pin Exp $
+
+DISTNAME=      heliocron-0.5.0
+CATEGORIES=    time
```
https://pkgsrc.se/time/heliocron

**Comment by mfreeborn** [comment]
My bad - I can't read. You are correct, thanks!
