### ISSUE TITLE
Read config from `/etc`

### ISSUE THREAD

**Issue by planetmarshall** [mfreeborn/heliocron#33]
Might be useful to read a configuration file from standard locations such as `/etc` and `/usr/local/etc`. Would submit a PR myself but don't speak Rust!

**Comment by mfreeborn** [comment]
I think I'm happy with the default config location to be in `~/.config`, but perhaps what I could do is add a `--config` option where the user can specify the path to the config file.

**Comment by planetmarshall** [comment]
Just wanted to say thanks for writing this - such a simple idea but really useful. Currently have it activating and deactivating my Solar PV monitoring software.
