### ISSUE TITLE
Useful utility

### ISSUE THREAD

**Issue by Chiny91** [mfreeborn/heliocron#35]
Not an issue but I can't find anywhere else to comment, so please delete comment if inappropriate.

I needed exactly this utility and it works a treat.   Easily installed by the R Pi binary although I did take a look at Rust and nearly persuaded myself to do it the hard way.

Anyway, to control my living room lamp, I now have an R Pi with heliocron, a bit of Python, MQTT, and wifi to a Chinese switch flashed with Tasmota.   What could possibly go wrong 😉

**Comment by mfreeborn** [comment]
That made my day, reading that :) Very pleased that you've gained some use out of it!
