### ISSUE TITLE
Multiple instances in cron

### ISSUE THREAD

**Issue by RobbyKilgore** [mfreeborn/heliocron#37]
I’m using Heliocron to schedule a Timelapse at sunrise, sunset, and with a different exposure after dark. If I kick them all off from a cron, they seem to fail. Or perhaps heliocron is not multithreaded? And only the last one triggered works?

I know the syntax is correct because I can run any of the commands manually from a shell. But if I trigger them all from cron at say 0 1 * * * even staggered by a minute two, they fail. 

Do I need to make sure there’s only one sleeping at a time from Cron?

**Comment by mfreeborn** [comment]
It's almost certainly a `cron` issue - first try using the absolute path to `heliocron` (i.e. `$ which heliocron`), and if that still doesn't work, try checking the logs. 

A command I just used to test was `@reboot /your/path/to/heliocron wait -e sunset >> /home/michael/cron.log 2>&1`

If you're still having problems, please reopen the issue.
