### ISSUE TITLE
cannot understand

### ISSUE THREAD

**Issue by patience4711** [mfreeborn/heliocron#38]
Hi, thank you for sharing this software.
However i don't understand how i can connect the numbers with the sunrise/set times that i get
from arduino libraries and my domoticz program, they calculate 8.37 sunrise and 16.30 sunset.

i am using it on a raspberry zero raspbian buster.
systemtime reports to be oke. Longitude and latitude are in the config file.

could you give me a hint on what i can do? I also have troubles to understand the +01:00 i see in the rows

> 

--------
Latitude: 51.4000N
Longitude: 5.4670W

DATE
----
2021-12-15 12:00:00 +01:00

Solar noon is at:         2021-12-15 13:17:05 +01:00
The day length is:        7h 52m 40s

Sunrise is at:            2021-12-15 09:20:45 +01:00
Sunset is at:             2021-12-15 17:13:25 +01:00

Civil dawn is at:         2021-12-15 08:40:42 +01:00
Civil dusk is at:         2021-12-15 17:53:29 +01:00

**Comment by mfreeborn** [comment]
Have you got your `E` and `W` mixed up? The coordinates you've got in that report puts you somewhere off the coast of Wales. Did you mean `5.4670E`, as in somewhere around Eindhoven?

The `+01:00` syntax is the timezone offset for your location.
