### ISSUE TITLE
Depending on seasons?

### ISSUE THREAD

**Issue by yetanothergithubaccount** [mfreeborn/heliocron#39]
Is it possible to allow the definition of heliocron jobs not only in relation to sunrise/sunset times, but also depending on the current season?
For example: a heater must not necessarily be turned on in the summer time.

**Comment by mfreeborn** [comment]
That's not supported and I can't envisage implementing it myself.

Your heater example is probably more dependent on the temperature, rather than the season, but I do understand your general point.
