### ISSUE TITLE
Does not work if system sleeps or is suspended

### ISSUE THREAD

**Issue by 4e554c4c** [mfreeborn/heliocron#43]
When my laptop goes to sleep, or is suspended, heliocron sleeps for far too long. I suspect this is because its main `std::thread::sleep` call does not make progress while the system itself is suspended. This is expected behavior according to the [sleep docs](https://doc.rust-lang.org/std/thread/fn.sleep.html), so heliocron shouldn't be using this call. A better alternative would probably be [sleep_until](https://docs.rs/tokio/latest/tokio/time/fn.sleep_until.html) from tokio, but that would require an async rewrite.

**Comment by 4e554c4c** [comment]
I tried rewriting the project using async and tokio (can PR if desired) but this did not help. `sleep_until` suffers from the same issue, as do other realtime clocks. the solution would probably be to use shorter sleeps; say ~10s

**Comment by 4e554c4c** [comment]
Would you accept a PR that adds a CFG to fix this only on unix systems?
I'm afraid I have no windows experience, so that's the furthest I'll be able to go fixing it.

**Comment by mfreeborn** [comment]
Yes, Unix-only for now is good. The primary target for heliocron was things like raspberry pis, where Unix OSes are ubiquitous.
