### ISSUE TITLE
Config File issue

### ISSUE THREAD

**Issue by jei-gaither** [mfreeborn/heliocron#52]
Howdy from Texas!

I stumbled upon Heliocron while working on a timelapse project designed to run on a RPi. I am trying to get it set up to use in crontab for launching my script at sunrise each day.

I love the elegance of your solution, thanks for contributing it to the world!

My issue is with setting my GPS location in the config file I created at ~/.config/heliocron.toml.

```
# ~/.config/heliocron.toml
# set the default location to Texas Capitol    
latitude = "30.274N"
longitude = "-97.740W"
```

Perhaps I'm doing something stoopid?

When I run _heliocron --version_, I get:
`Config error: Error parsing TOML file. Ensure that it is of the correct format.`

**Comment by mfreeborn** [comment]
Good evening :)

Try removing that `-`. I should probably make the error message a bit clearer!

**Comment by jei-gaither** [comment]
Oh, of course!!! The negative would make it W. 🤦‍♂️

Thanks for the quick and gracious response! 👍

**Comment by mfreeborn** [comment]
Super :)
