### ISSUE TITLE
README.md needs updating?

### ISSUE THREAD

**Issue by Sadi58** [mfreeborn/heliocron#63]
I've just noticed that some instructions and examples in README.md file might need updating.
It seems helicron no longer uses symbols N, S, E, and W; instead we should use numerical values only for North (N) and East (E), and a minus sign before numerical values for South (S) and West (W).

Additionaly, the values in the configuration file shouldn't be quoted, and that section should be changed like this:
```
# set the default location to Buckingham Palace
latitude = 51.5014
longitude = -0.1419
```

**Comment by mfreeborn** [comment]
There's always something! Well spotted and thank you for reporting. A pull request will close this issue momentarily once checks are complete.
