### ISSUE TITLE
Build on MacOs

### ISSUE THREAD

**Issue by phgz** [mfreeborn/heliocron#66]
Hi,

When I try to build (**rustc 1.65.0 (897e37553 2022-11-02)**) the project (**v0.8.1**) on **arm64-apple-darwin22.1.0** (**MacOs 13.0 (22A380)**), I get a compilation error for **tokio-walltime v0.1.2**. Errors are of the kind
```error[E0425]: cannot find function `timer_create` in crate libc```.
I tried on Linux and I had no problem.

I'm not sure what I should be looking for, I'm not a rust expert.

Otherwise, the plugin seems nice!

**Comment by mfreeborn** [comment]
Linux is the only supported operating system, due to the dependency on `tokio-walltime`. I don't use MacOS so it's not aa feature I would personally be in a position to add.
