### ISSUE TITLE
Doesn't seem to be working through cron

### ISSUE THREAD

**Issue by g6nhu** [mfreeborn/heliocron#72]
Hi,

I've installed heliocron as I have scripts that I'd like to run at sunrise and sunset but they're not running.  When I use 'heliocron report' I do get the correct results so I know it's installed properly.

In my crontab, I have the following (I've hidden my lat/long):

00 15 * * * heliocron --latitude xx.xxxx --longitude yyy.yyyy wait --event sunset \ && /usr/local/bin/dim.sh

00 02 * * * heliocron --latitude xx.xxxx --longitude yyy.yyyy wait --event sunrise \ && /usr/local/bin/brighten.sh

I do have the correct lat long configured in .config/heliocron.toml but added them in the cron entries just in case they were specifically needed there.  I've tried without as well.

But nothing happens at sunrise or sunset, my scripts aren't run.

Have I missed something really obvious please?

I'm using a Raspberry Pi with Raspbian Stretch.  It needs to be Stretch, what I'm running won't work with a later version.

Thanks.

**Comment by bgro82** [comment]
I think you may want "... && sh /usr/local/bin/dim.sh"?

**Comment by g6nhu** [comment]
Thanks. Tried that

30 15 * * * heliocron --latitude xx.yyyy --longitude yyy.yyyy wait --event sunset \ && sh /usr/local/bin/dim.sh

Didn't do anything.

**Comment by bgro82** [comment]
ok, a few other things I'd try:
- remove the "\" after sunset
- specify the full path to heliocron (for me it is /home/pi/helicron for example)

**Comment by g6nhu** [comment]
Bingo, that worked, thanks.

00 15 * * * /home/pi/.cargo/bin/heliocron --latitude xx.xxxx --longitude yyy.yyyy wait --event sunset && sh /usr/local/bin/dim.sh
